# Generated by Django 4.2 on 2023-04-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='город/страна')),
            ],
            options={
                'verbose_name': 'категория предложений',
                'verbose_name_plural': 'категории предложений',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('TelNum', models.CharField(max_length=150, verbose_name='tel.number')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='Photos/%Y/%m/%d', verbose_name='иконка сервиса')),
                ('title', models.CharField(max_length=100, verbose_name='название сервиса')),
                ('photo', models.ImageField(blank=True, upload_to='Photos/%Y/%m/%d', verbose_name='фотография примера сервиса')),
                ('availability', models.BooleanField(default=True)),
                ('info', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'cервисы',
                'verbose_name_plural': 'cервисы',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='Photos/%Y/%m/%d', verbose_name='фотография города(страны)')),
                ('title', models.CharField(max_length=150, verbose_name='имя города/страны')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('info', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100, verbose_name='Lokatsiya')),
                ('days', models.IntegerField(verbose_name='Days')),
                ('mark', models.IntegerField(verbose_name='Otsenka')),
                ('nights', models.IntegerField(verbose_name='Nights')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('is_published', models.BooleanField(default=True, verbose_name='Доступность')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aynTravelApp.cat')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения',
                'ordering': ['title'],
            },
        ),
    ]
