# Generated by Django 4.2 on 2023-04-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='location',
            new_name='location1',
        ),
    ]
