# Generated by Django 4.2 on 2023-04-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0002_rename_location_offer_location1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='location1',
        ),
    ]
