# Generated by Django 4.1.5 on 2023-04-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0005_about_alter_offer_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'информация', 'verbose_name_plural': 'информация'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['title'], 'verbose_name': 'категория турпакета', 'verbose_name_plural': 'категории турпакетов'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['title'], 'verbose_name': 'турпакет', 'verbose_name_plural': 'турпакеты'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='days',
            field=models.IntegerField(verbose_name='Сколько дней?'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location1',
            field=models.CharField(max_length=100, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='mark',
            field=models.IntegerField(verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='nights',
            field=models.IntegerField(verbose_name='Сколько ночей?'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Photos/%Y/%m/%d', verbose_name='фотография турпакета'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название турпакета'),
        ),
    ]
