# Generated by Django 4.2 on 2023-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0006_alter_about_options_alter_cat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Url'),
        ),
    ]
