# Generated by Django 4.2 on 2023-04-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0009_offer_categor_alter_offer_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TCategory',
        ),
    ]
