# Generated by Django 4.2 on 2023-04-21 05:11

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0010_rename_category_tcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='categor',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='slug',
        ),
        migrations.AddField(
            model_name='offer',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
        migrations.DeleteModel(
            name='TCategory',
        ),
    ]
