# Generated by Django 4.2 on 2023-04-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0011_remove_cat_slug_remove_offer_categor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'турпакет', 'verbose_name_plural': 'турпакеты'},
        ),
    ]
