# Generated by Django 4.2 on 2023-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0012_alter_offer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'категория турпакета', 'verbose_name_plural': 'категории турпакетов'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['title'], 'verbose_name': 'турпакет', 'verbose_name_plural': 'турпакеты'},
        ),
        migrations.RemoveField(
            model_name='cat',
            name='title',
        ),
        migrations.AddField(
            model_name='cat',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='название турпакета'),
        ),
        migrations.AddField(
            model_name='cat',
            name='country',
            field=models.CharField(blank=True, max_length=150, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='cat',
            name='mark',
            field=models.IntegerField(null=True, verbose_name='оценка'),
        ),
    ]
