# Generated by Django 4.2 on 2023-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0014_cat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
