# Generated by Django 4.2 on 2023-04-21 08:41

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0015_cat_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text')),
                ('author', models.CharField(max_length=50, verbose_name='Опрератор')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('photo', models.FileField(blank=True, null=True, upload_to='Photos/%Y/%m/%d', verbose_name='фотография опрератора')),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='info',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='location1',
        ),
    ]
