# Generated by Django 4.2 on 2023-04-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0016_operator_alter_about_options_remove_offer_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы'},
        ),
    ]
