# Generated by Django 4.2 on 2023-04-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0018_contactfrom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFrom',
            new_name='ContactForm',
        ),
    ]
