# Generated by Django 4.2 on 2023-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0019_rename_contactfrom_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='about',
            name='info_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='info_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='info_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='city_en',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='название турпакета'),
        ),
        migrations.AddField(
            model_name='cat',
            name='city_ru',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='название турпакета'),
        ),
        migrations.AddField(
            model_name='cat',
            name='city_uz',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='название турпакета'),
        ),
        migrations.AddField(
            model_name='cat',
            name='country_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='cat',
            name='country_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='cat',
            name='country_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='info_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='info_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='info_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='author_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Опрератор'),
        ),
        migrations.AddField(
            model_name='operator',
            name='author_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Опрератор'),
        ),
        migrations.AddField(
            model_name='operator',
            name='author_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Опрератор'),
        ),
        migrations.AddField(
            model_name='operator',
            name='post_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='operator',
            name='post_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='operator',
            name='post_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
