# Generated by Django 4.2 on 2023-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0020_delete_services_about_info_en_about_info_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название турпакета'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название турпакета'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название турпакета'),
        ),
    ]
