# Generated by Django 4.2 on 2023-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0021_offer_title_en_offer_title_ru_offer_title_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='text',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
