# Generated by Django 4.2 on 2023-04-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0023_contact_email_contact_link_fc_contact_link_ins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='working_time',
            field=models.CharField(max_length=150, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='TelNum',
            field=models.CharField(max_length=150, verbose_name='номер телефона'),
        ),
    ]
