# Generated by Django 4.2 on 2023-04-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0024_contact_working_time_alter_contact_telnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='working_time_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='working_time_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='working_time_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Время работы'),
        ),
    ]
