# Generated by Django 4.2 on 2023-04-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynTravelApp', '0025_contact_working_time_en_contact_working_time_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='author_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='author_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='author_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Оператор'),
        ),
    ]
